function plotDemInter(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 10-Apr-2020 13:05:01

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'Marker','o','Color',[0 0 0]);

% Create xlabel
xlabel({'(a)'},'FontSize',9,'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[203.691387675808 204.739998651849]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[639.989822059588 670.41903236683]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'XTick',zeros(1,0),'YTick',zeros(1,0));
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'Marker','o','Color',[0 0 0]);

% Create xlabel
xlabel({'(b)'},'FontSize',9,'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[1021.03560801799 1021.60639856521]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[67.3774210222775 68.5964664860258]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'XTick',zeros(1,0),'YTick',zeros(1,0));
