function plotCorrDisShift(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-May-2020 16:25:12

% Create figure
figure1 = figure('WindowState','maximized','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 0]);

% Create ylabel
ylabel({'r_x_y[m]'},'FontName','Times New Roman');

% Create xlabel
xlabel({'Distance (m)'},'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1800 max(X1)]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.0188649336687087]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9);
