function plotIdealNoisy(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-May-2020 00:44:57

% Create figure
figure1 = figure('WindowState','maximized','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','y[n] with SNR = -14 dB','Color',[0.8 0.8 0.8]);
set(plot1(2),'DisplayName','y[n] with no noise.','LineWidth',3,...
    'Color',[0 0 0]);

% Create ylabel
ylabel({'Amplitude (V)'},'FontName','Times New Roman');

% Create xlabel
xlabel({'Time (\mus)'},'FontName','Times New Roman');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9);
% Create legend
legend(axes1,'show');

