function plotTxRx(xaxis, tx, rx)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 31-Mar-2020 17:33:30

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(xaxis,tx,'Parent',subplot1,'Color',[0 0 0]);


% Create xlabel
xlabel({'(a)'},'FontSize',9,'FontName','Times New Roman');



% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 1.0194]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[-0.047 0.64]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'XTick',zeros(1,0),'XTickLabel',{},'YTick',[0 0.6],...
    'YTickLabel',{'0','0.6'});
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.170046189376443 0.775 0.341162790697674]);
hold(axes1,'on');

% Create plot
plot(xaxis,rx,'Parent',axes1,'Color',[0 0 0]);

% Create xlabel
xlabel({'(b)'},'FontSize',9,'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 1.0194]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.0084 0.0921]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9,'XTick',zeros(1,0),...
    'YTick',[0.01 0.08],'YTickLabel',{'0.01','0.08'});
