function plotAttenuationResults(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Apr-2020 18:46:46

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Correlation SNR','Marker','+');
set(plot1(2),'DisplayName','Correlation Suppression','Marker','o');

% Create ylabel
ylabel({'[dB]'},'FontName','Times New Roman');

% Create xlabel
xlabel({'Attenuation [dB]'},'FontName','Times New Roman');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9);
% Create legend
legend(axes1,'show');

