function plotMSeqFreq(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 12-May-2020 19:08:35

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 0]);

% Create ylabel
ylabel({'Spectral Power'},'FontName','Times New Roman');

% Create xlabel
xlabel({'Frecuency [MHz]'},'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 119.845360824742]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 0.134166666666667]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9,'TickLength',[0 0],...
    'XTick',[0 20 40 60 80 100],'YTick',[0 0.1269],'YTickLabel',{'0','4 a^2'});
