function plotCorrTimeShift(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 12-May-2020 22:29:40

% Create figure
figure1 = figure('WindowState','maximized','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 0]);

% Create ylabel
ylabel({'r_x_y[m]'},'FontName','Times New Roman');
ylim(axes1,[-0.05*max(Y1) 1.05*max(Y1)]);

% Create xlabel
xlabel({'m'},'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-max(X1) max(X1)]);
box(axes1,'on');
% Set the remaining axes properties

set(axes1,'FontName','Times New Roman','FontSize',9,'YTick',[0 max(Y1)],...
    'YTickLabel',{'0','N P_x'});
