function plotQualityFPGA(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 16-May-2020 18:10:03

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Correlation SNR with ideal shift','Marker','+');
set(plot1(2),'DisplayName','Correlation Suppression with ideal shift',...
    'Marker','o');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Color',[0 0 0]);
set(plot2(1),'DisplayName','Correlation SNR with random shift',...
    'Marker','diamond');
set(plot2(2),'DisplayName','Correlation Suppression with random shift',...
    'Marker','^');

% Create ylabel
ylabel({'dB'});

% Create xlabel
xlabel({'SNR y[n] (dB)'});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-21 -9]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.166666676458858 0.660600559562682 0.419642847350666 0.23469387122563]);

