function plotDemInter(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 13-May-2020 08:27:30

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'Marker','o','Color',[0 0 0]);

% Create ylabel
ylabel({'r_x_y[m]'},'FontSize',9,'FontName','Times New Roman');

% Create xlabel
xlabel({'Delay'},'FontSize',9,'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[1715.52265539496 1798.22489706633]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[0 3.65392850715805]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'XTick',zeros(1,0),'YTick',zeros(1,0));
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'Marker','o','Color',[0 0 0]);

% Create ylabel
ylabel({'r_x_y[m]'},'FontSize',9,'FontName','Times New Roman');

% Create xlabel
xlabel({'Delay'},'FontSize',9,'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[981.726115011567 1063.91164468397]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[-0.000819901479104951 0.380166927126728]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'XTick',zeros(1,0),'YTick',zeros(1,0));
