function plotMSeqTime(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Mar-2020 11:56:29

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 0]);

% Create xlabel
xlabel({'Time'},'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10.194]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.25 1.25]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9,'XTick',zeros(1,0),...
    'YTick',zeros(1,0));
