function plotExInterpole(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 13-Apr-2020 11:34:19

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','o','LineWidth',2,'LineStyle','none','Color',[0 0 0]);

% Create plot
plot(X2,Y2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y3,'Marker','o','LineWidth',1,'Color',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.1 3.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.05 2.1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',zeros(1,0),'YTick',7);
% Create textbox
annotation(figure1,'textbox',...
    [0.312550165250237 0.233333333333333 0.101047568460812 0.0959501557632401],...
    'String','(x1, h1)',...
    'FontSize',9,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.646833333333334 0.629166666666667 0.103874881964116 0.131996365524401],...
    'String','(x2, h2)',...
    'FontSize',9,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.591104166666667 0.917004153686396 0.23750773135033 0.0249221183800621],...
    'String','(Interpole(x1, x2), h)',...
    'FontSize',9,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

