function plotSamplingResultsQuality(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Apr-2020 21:21:22

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Color',[0 0 0],'Parent',axes1);
set(plot1(1),'DisplayName','SNR y[n] (1022 m reel)','Marker','o',...
    'LineStyle','--');
set(plot1(2),'DisplayName','SNR y[n] (attenuation = 53 dB)','Marker','x',...
    'LineStyle','--');
set(plot1(3),'DisplayName','SNR Correlation (1022 m reel)','Marker','+');
set(plot1(4),'DisplayName','SNR Correlation (attenuation = 53 dB)',...
    'Marker','*');

% Create ylabel
ylabel({'dB'});

% Create xlabel
xlabel({'Smaples'});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 11]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-25 25]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',9,'XTick',[1 2 4 10],...
    'YTick',[-25 0 25]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.601066184398023 0.367816224446673 0.288335511092273 0.173192766416504]);

